# Generated by Django 4.2.16 on 2026-05-16 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0008_contrat_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="date_debut",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AddField(
            model_name="contrat",
            name="date_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AddField(
            model_name="contrat",
            name="delai_paiement",
            field=models.CharField(
                choices=[
                    ("15J", "15 jours"),
                    ("30J", "30 jours"),
                    ("30JFDM", "30 jours fin de mois"),
                    ("60J", "60 jours"),
                    ("60JFDM", "60 jours fin de mois"),
                    ("90J", "90 jours"),
                    ("90JFDM", "90 jours fin de mois"),
                    ("120J", "120 jours"),
                    ("120JFDM", "120 jours fin de mois"),
                ],
                default="90JFDM",
                max_length=10,
                verbose_name="Délai de paiement",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="objet",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Objet du contrat"
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="taux_de_TVA",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
                verbose_name="Taux de TVA par defaut",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_realisation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de base d'échéance"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="partie_liee",
            field=models.BooleanField(
                default=False, verbose_name="Tout contrat nécessite validation"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="date_accord_ca",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de l'accord du CA"
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="date_signature",
            field=models.DateField(verbose_name="Date de signature"),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="is_actif",
            field=models.BooleanField(default=True, verbose_name="Contrat actif"),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="is_solde",
            field=models.BooleanField(default=False, verbose_name="Contrat soldé"),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="montant_ht",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant HT"
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avenants",
                to="clients.contrat",
                verbose_name="Contrat parent ou dernier avenant",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="taux_ras_is",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux de RAS IS par defaut",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="taux_ras_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=75,
                max_digits=5,
                verbose_name="Taux de RAS TVA par defaut",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="date_echeance",
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="date_emission",
            field=models.DateField(verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
