# Generated by Django 4.2.16 on 2026-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_contrat_date_debut_contrat_date_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Montant total du paiement",
            ),
        ),
    ]
