# Generated by Django 5.2.16 on 2026-07-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_paiement_montant_total'),
        ('fournisseurs', '0015_alter_beneficiaire_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'beneficiaire__raison_sociale': 'Idara', 'type_compte': 'bancaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_encaissement', to='fournisseurs.comptetresorerie'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='compte_bancaire',
            field=models.ForeignKey(limit_choices_to={'beneficiaire__raison_sociale': 'Idara', 'type_compte': 'bancaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaissement', to='fournisseurs.comptetresorerie'),
        ),
    ]
