services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: idara-local-dev:latest
    working_dir: /app
    user: "0:0"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/app
    ports:
      - "8000:8000"